//! AmneziaWG configuration file generation.
//!
//! Pure AmneziaWG — all configs use `awg`-compatible format with
//! obfuscation parameters.

use crate::db;
use anyhow::Result;

fn parse_json_arr(s: &str) -> Vec<String> {
    serde_json::from_str(s).unwrap_or_default()
}

fn server_ip(cidr: &str) -> String {
    if let Ok(net) = cidr.parse::<ipnet::Ipv4Net>() {
        let ip = std::net::Ipv4Addr::from(u32::from(net.addr()) + 1);
        return format!("{}/{}", ip, net.prefix_len());
    }
    if let Ok(net) = cidr.parse::<ipnet::Ipv6Net>() {
        let ip = std::net::Ipv6Addr::from(u128::from(net.addr()) + 1);
        return format!("{}/{}", ip, net.prefix_len());
    }
    cidr.to_string()
}

fn sanitize_for_shell(s: &str) -> String {
    s.chars()
        .filter(|c| c.is_alphanumeric() || matches!(c, '.' | '-' | '_' | '/' | ':'))
        .collect()
}

fn expand(template: &str, device: &str, port: &str, v4: &str, v6: &str) -> String {
    template
        .replace("{{device}}", &sanitize_for_shell(device))
        .replace("{{port}}", &sanitize_for_shell(port))
        .replace("{{ipv4Cidr}}", &sanitize_for_shell(v4))
        .replace("{{ipv6Cidr}}", &sanitize_for_shell(v6))
}

/// Generate server [Interface] section.
pub fn generate_server_interface(iface: &db::Interface, hooks: &db::Hooks) -> Result<String> {
    let port = iface.port.to_string();
    let v4 = server_ip(&iface.ipv4_cidr);
    let v6 = server_ip(&iface.ipv6_cidr);
    let addr = if crate::config::CONFIG.disable_ipv6 {
        v4.clone()
    } else {
        format!("{}, {}", v4, v6)
    };

    let mut awg = vec![
        format!("Jc = {}", iface.j_c),
        format!("Jmin = {}", iface.j_min),
        format!("Jmax = {}", iface.j_max),
        format!("S1 = {}", iface.s1),
        format!("S2 = {}", iface.s2),
    ];
    if let Some(v) = iface.s3 { if v > 0 { awg.push(format!("S3 = {}", v)); } }
    if let Some(v) = iface.s4 { if v > 0 { awg.push(format!("S4 = {}", v)); } }
    if !iface.h1.is_empty() { awg.push(format!("H1 = {}", iface.h1)); }
    if !iface.h2.is_empty() { awg.push(format!("H2 = {}", iface.h2)); }
    if !iface.h3.is_empty() { awg.push(format!("H3 = {}", iface.h3)); }
    if !iface.h4.is_empty() { awg.push(format!("H4 = {}", iface.h4)); }
    if !iface.i1.is_empty() { awg.push(format!("I1 = {}", iface.i1)); }
    if !iface.i2.is_empty() { awg.push(format!("I2 = {}", iface.i2)); }
    if !iface.i3.is_empty() { awg.push(format!("I3 = {}", iface.i3)); }
    if !iface.i4.is_empty() { awg.push(format!("I4 = {}", iface.i4)); }
    if !iface.i5.is_empty() { awg.push(format!("I5 = {}", iface.i5)); }
    // J1/J2/J3/Itime are NOT in the canonical AmneziaWG 2.0 spec —
    // amneziawg-tools/src/config.c does not parse them and awg-quick will
    // reject the resulting file with `Unknown key`. We keep the DB columns
    // for drop-in compatibility with upstream awg-easy DBs but never emit
    // them to disk.

    Ok(format!(
        "# Note: Do not edit this file directly.\n\
         # Your changes will be overwritten!\n\n\
         # Server\n\
         [Interface]\n\
         PrivateKey = {pk}\n\
         Address = {addr}\n\
         ListenPort = {port}\n\
         MTU = {mtu}\n\
         {awg}\n\
         PreUp = {pre_up}\n\
         PostUp = {post_up}\n\
         PreDown = {pre_down}\n\
         PostDown = {post_down}",
        pk = iface.private_key,
        addr = addr,
        port = iface.port,
        mtu = iface.mtu,
        awg = awg.join("\n"),
        pre_up = expand(&hooks.pre_up, &iface.device, &port, &iface.ipv4_cidr, &iface.ipv6_cidr),
        post_up = expand(&hooks.post_up, &iface.device, &port, &iface.ipv4_cidr, &iface.ipv6_cidr),
        pre_down = expand(&hooks.pre_down, &iface.device, &port, &iface.ipv4_cidr, &iface.ipv6_cidr),
        post_down = expand(&hooks.post_down, &iface.device, &port, &iface.ipv4_cidr, &iface.ipv6_cidr),
    ))
}

/// Generate a [Peer] section for an enabled client.
pub fn generate_server_peer(client: &db::Client) -> Result<String> {
    let ipv4 = client.ipv4_address.as_deref().unwrap_or("0.0.0.0");
    let ipv6 = client.ipv6_address.as_deref().unwrap_or("::");
    let psk = client.pre_shared_key.as_deref().unwrap_or("");

    let mut allowed = vec![format!("{}/32", ipv4)];
    if !crate::config::CONFIG.disable_ipv6 {
        allowed.push(format!("{}/128", ipv6));
    }
    if let Some(ref sai) = client.server_allowed_ips {
        allowed.extend(parse_json_arr(sai));
    }

    let mut extra = String::new();
    if let Some(ref ep) = client.server_endpoint {
        if !ep.is_empty() {
            extra.push_str(&format!("\nEndpoint = {}", ep));
        }
    }
    // Per-peer AmneziaWG opt-in. When set, awg-tools forwards the value to
    // the kernel's WGPEER_A_ADVANCED_SECURITY netlink attribute. When
    // unset, the kernel auto-detects from the H1 magic header on the first
    // incoming handshake (noise.c:601-633).
    if let Some(adv) = client.advanced_security {
        extra.push_str(&format!(
            "\nAdvancedSecurity = {}",
            if adv { "on" } else { "off" }
        ));
    }

    let safe_name = client.name.replace('\n', " ").replace('\r', " ");

    Ok(format!(
        "# Client: {name} ({id})\n\
         [Peer]\n\
         PublicKey = {pubkey}\n\
         PresharedKey = {psk}\n\
         AllowedIPs = {allowed}{extra}",
        name = safe_name,
        id = client.id,
        pubkey = client.public_key,
        psk = psk,
        allowed = allowed.join(", "),
        extra = extra,
    ))
}

/// Generate a complete client .conf file.
pub fn generate_client_config(
    iface: &db::Interface,
    user_config: &db::UserConfig,
    client: &db::Client,
) -> Result<String> {
    let ipv4 = client.ipv4_address.as_deref().unwrap_or("0.0.0.0");
    let ipv6 = client.ipv6_address.as_deref().unwrap_or("::");
    let psk = client.pre_shared_key.as_deref().unwrap_or("");

    let addr = if crate::config::CONFIG.disable_ipv6 {
        format!("{}/32", ipv4)
    } else {
        format!("{}/32, {}/128", ipv4, ipv6)
    };

    // DNS: client > user_config default
    let dns_list = match client.dns.as_deref() {
        Some(s) if !s.is_empty() => parse_json_arr(s),
        _ => parse_json_arr(&user_config.default_dns),
    };
    let dns_line = if dns_list.is_empty() {
        String::new()
    } else {
        format!("\nDNS = {}", dns_list.join(", "))
    };

    // AllowedIPs: client > user_config default
    let allowed_list = match client.allowed_ips.as_deref() {
        Some(s) if !s.is_empty() => parse_json_arr(s),
        _ => parse_json_arr(&user_config.default_allowed_ips),
    };

    // Hooks
    let mut hooks = Vec::new();
    if let Some(ref s) = client.pre_up { if !s.is_empty() { hooks.push(format!("PreUp = {}", s)); } }
    if let Some(ref s) = client.post_up { if !s.is_empty() { hooks.push(format!("PostUp = {}", s)); } }
    if let Some(ref s) = client.pre_down { if !s.is_empty() { hooks.push(format!("PreDown = {}", s)); } }
    if let Some(ref s) = client.post_down { if !s.is_empty() { hooks.push(format!("PostDown = {}", s)); } }

    // AWG params
    let jc = client.j_c.unwrap_or(iface.j_c);
    let jmin = client.j_min.unwrap_or(iface.j_min);
    let jmax = client.j_max.unwrap_or(iface.j_max);

    let mut awg = vec![
        format!("Jc = {}", jc),
        format!("Jmin = {}", jmin),
        format!("Jmax = {}", jmax),
        format!("S1 = {}", iface.s1),
        format!("S2 = {}", iface.s2),
    ];
    if let Some(v) = iface.s3 { if v > 0 { awg.push(format!("S3 = {}", v)); } }
    if let Some(v) = iface.s4 { if v > 0 { awg.push(format!("S4 = {}", v)); } }
    if !iface.h1.is_empty() { awg.push(format!("H1 = {}", iface.h1)); }
    if !iface.h2.is_empty() { awg.push(format!("H2 = {}", iface.h2)); }
    if !iface.h3.is_empty() { awg.push(format!("H3 = {}", iface.h3)); }
    if !iface.h4.is_empty() { awg.push(format!("H4 = {}", iface.h4)); }

    if let Some(ref s) = client.i1 { if !s.is_empty() { awg.push(format!("I1 = {}", s)); } }
    if let Some(ref s) = client.i2 { if !s.is_empty() { awg.push(format!("I2 = {}", s)); } }
    if let Some(ref s) = client.i3 { if !s.is_empty() { awg.push(format!("I3 = {}", s)); } }
    if let Some(ref s) = client.i4 { if !s.is_empty() { awg.push(format!("I4 = {}", s)); } }
    if let Some(ref s) = client.i5 { if !s.is_empty() { awg.push(format!("I5 = {}", s)); } }
    // J1/J2/J3/Itime intentionally not emitted — see note in
    // generate_server_interface() above.

    // From the client's perspective the [Peer] block represents the
    // server. We're a pure-AmneziaWG deployment, so the client should
    // always treat the server as advanced. If the operator explicitly set
    // a tri-state value on the client row we honour it; otherwise default
    // to `on` (mirrors the server's effective behaviour).
    let adv_line = match client.advanced_security {
        Some(true) => "\nAdvancedSecurity = on",
        Some(false) => "\nAdvancedSecurity = off",
        None => "\nAdvancedSecurity = on",
    };

    Ok(format!(
        "[Interface]\n\
         PrivateKey = {privkey}\n\
         Address = {addr}\n\
         MTU = {mtu}{dns}\n\
         {hooks}\
         {awg}\n\
         [Peer]\n\
         PublicKey = {srv_pubkey}\n\
         PresharedKey = {psk}\n\
         AllowedIPs = {allowed}\n\
         PersistentKeepalive = {ka}\n\
         Endpoint = {host}:{port}{adv}",
        privkey = client.private_key,
        addr = addr,
        mtu = client.mtu,
        dns = dns_line,
        hooks = if hooks.is_empty() { String::new() } else { format!("{}\n", hooks.join("\n")) },
        awg = awg.join("\n"),
        srv_pubkey = iface.public_key,
        psk = psk,
        allowed = allowed_list.join(", "),
        ka = client.persistent_keepalive,
        host = user_config.host,
        port = user_config.port,
        adv = adv_line,
    ))
}
