//! `server_config.toml` generator for MasterDnsVPN.
//!
//! Pure function: takes a `db::MdnsvpnInbound` + the runtime directory
//! and produces a TOML body the supervisor writes to
//! `<mdnsvpn_dir>/server_config.toml`. The supervisor restarts mdnsvpn
//! after every config change — the upstream binary doesn't expose a
//! SIGHUP / `notify`-style hot-reload that we can rely on, so re-spawn
//! is the safe path.
//!
//! Validation: refuses obviously-broken combinations (no domains, port
//! out of range, illegal encryption method, TCP-mode without a forward
//! target, etc.). Server-side validation is duplicated in
//! `api/mdnsvpn.rs` so bad PUTs return 4xx, but doing it here too means
//! the supervisor never spawns mdnsvpn with an obviously-broken file.

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{anyhow, Result};

use crate::db::MdnsvpnInbound;
use crate::mdnsvpn::keys;

/// Filename mdnsvpn reads the shared key from. Lives next to
/// `server_config.toml` under `mdnsvpn_dir`.
pub const KEY_FILENAME: &str = "encrypt_key.txt";

/// Build the `server_config.toml` body for the given inbound. The
/// runtime directory is used as the parent of the key file
/// (`encrypt_key.txt`).
pub fn generate(inbound: &MdnsvpnInbound, mdnsvpn_dir: &Path) -> Result<String> {
    validate(inbound)?;

    let domains: Vec<String> = parse_json_string_array(&inbound.domains)
        .map_err(|e| anyhow!("MasterDnsVPN domains: {e}"))?;
    if domains.is_empty() {
        return Err(anyhow!(
            "MasterDnsVPN inbound has no `domains` — set at least one NS-delegated FQDN"
        ));
    }
    let upstreams: Vec<String> = parse_json_string_array(&inbound.dns_upstream_servers)
        .map_err(|e| anyhow!("MasterDnsVPN dns_upstream_servers: {e}"))?;

    let mut body = String::new();
    writeln!(body, "# Generated by awg-easy-rs — do NOT edit by hand.").unwrap();
    writeln!(body, "# Bumped on every admin save; manual edits are overwritten.").unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 1) Tunnel policy
    // ------------------------------------------------------------------
    writeln!(body, "DOMAIN = {}", toml_string_array(&domains)).unwrap();
    writeln!(body, "PROTOCOL_TYPE = {}", toml_string(&inbound.protocol_type)).unwrap();
    body.push('\n');

    // Default to upstream's "everything is allowed" compression set.
    // Operators tweak via `additional_config` if they need to lock it
    // down.
    writeln!(body, "SUPPORTED_UPLOAD_COMPRESSION_TYPES = [0, 1, 2, 3]").unwrap();
    writeln!(body, "SUPPORTED_DOWNLOAD_COMPRESSION_TYPES = [0, 1, 2, 3]").unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 2) UDP listener
    // ------------------------------------------------------------------
    writeln!(body, "UDP_HOST = {}", toml_string(&inbound.bind)).unwrap();
    writeln!(body, "UDP_PORT = {}", inbound.port).unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 5) DNS tunnel upstream
    // ------------------------------------------------------------------
    if !upstreams.is_empty() {
        writeln!(
            body,
            "DNS_UPSTREAM_SERVERS = {}",
            toml_string_array(&upstreams)
        )
        .unwrap();
    }
    body.push('\n');

    // ------------------------------------------------------------------
    // 6) Upstream SOCKS / forwarding
    // ------------------------------------------------------------------
    writeln!(
        body,
        "USE_EXTERNAL_SOCKS5 = {}",
        bool_lit(inbound.use_external_socks5)
    )
    .unwrap();
    writeln!(body, "SOCKS5_AUTH = {}", bool_lit(inbound.socks5_auth)).unwrap();
    if inbound.socks5_auth {
        writeln!(body, "SOCKS5_USER = {}", toml_string(&inbound.socks5_user)).unwrap();
        writeln!(body, "SOCKS5_PASS = {}", toml_string(&inbound.socks5_pass)).unwrap();
    }
    writeln!(body, "FORWARD_IP = {}", toml_string(&inbound.forward_ip)).unwrap();
    writeln!(body, "FORWARD_PORT = {}", inbound.forward_port).unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 7) Security
    // ------------------------------------------------------------------
    writeln!(
        body,
        "DATA_ENCRYPTION_METHOD = {}",
        inbound.encryption_method
    )
    .unwrap();
    let key_path = mdnsvpn_dir.join(KEY_FILENAME);
    writeln!(
        body,
        "ENCRYPTION_KEY_FILE = {}",
        toml_string(&key_path.to_string_lossy())
    )
    .unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // 9) Logging
    // ------------------------------------------------------------------
    writeln!(body, "LOG_LEVEL = \"INFO\"").unwrap();
    body.push('\n');

    // ------------------------------------------------------------------
    // Verbatim escape hatch
    // ------------------------------------------------------------------
    let extra = inbound.additional_config.trim();
    if !extra.is_empty() {
        writeln!(body, "# --- operator additional_config (verbatim) ---").unwrap();
        body.push_str(extra);
        if !body.ends_with('\n') {
            body.push('\n');
        }
    }

    Ok(body)
}

/// Validate the inbound for "could mdnsvpn actually run with this?".
/// Cheap structural checks only — DNS reachability of `domains`,
/// NS-delegation correctness, etc. are deployment concerns.
pub fn validate(inbound: &MdnsvpnInbound) -> Result<()> {
    if inbound.port < 1 || inbound.port > 65535 {
        return Err(anyhow!(
            "MasterDnsVPN port must be 1..=65535, got {}",
            inbound.port
        ));
    }
    keys::validate_encryption_method(inbound.encryption_method)?;
    keys::validate_key(&inbound.encryption_key)?;

    // Domains array sanity. We don't try to validate the LDH grammar
    // here — operators sometimes use IDN-ish names or trailing-dot FQDNs;
    // mdnsvpn itself accepts whatever the JSON unwraps to.
    let domains = parse_json_string_array(&inbound.domains)
        .map_err(|e| anyhow!("MasterDnsVPN domains: {e}"))?;
    if domains.is_empty() {
        return Err(anyhow!(
            "MasterDnsVPN inbound has no `domains` — set at least one NS-delegated FQDN"
        ));
    }
    for d in &domains {
        let t = d.trim();
        if t.is_empty() || t.contains(' ') || t.contains('\t') {
            return Err(anyhow!(
                "MasterDnsVPN domain {d:?} contains whitespace or is empty"
            ));
        }
    }

    // Protocol type: only the two upstream-supported values are accepted.
    match inbound.protocol_type.as_str() {
        "SOCKS5" | "TCP" => {}
        other => {
            return Err(anyhow!(
                "MasterDnsVPN protocol_type must be \"SOCKS5\" or \"TCP\", got {other:?}"
            ))
        }
    }

    // TCP mode requires a forward target.
    if inbound.protocol_type == "TCP" {
        if inbound.forward_ip.trim().is_empty() {
            return Err(anyhow!(
                "MasterDnsVPN protocol_type=TCP requires a non-empty forward_ip"
            ));
        }
        if inbound.forward_port < 1 || inbound.forward_port > 65535 {
            return Err(anyhow!(
                "MasterDnsVPN protocol_type=TCP requires forward_port in 1..=65535 \
                 (got {})",
                inbound.forward_port
            ));
        }
    }
    // SOCKS5-with-external requires forward_ip + forward_port too.
    if inbound.protocol_type == "SOCKS5" && inbound.use_external_socks5 {
        if inbound.forward_ip.trim().is_empty() {
            return Err(anyhow!(
                "MasterDnsVPN use_external_socks5=true requires a non-empty forward_ip"
            ));
        }
        if inbound.forward_port < 1 || inbound.forward_port > 65535 {
            return Err(anyhow!(
                "MasterDnsVPN use_external_socks5=true requires forward_port \
                 in 1..=65535 (got {})",
                inbound.forward_port
            ));
        }
    }
    if inbound.socks5_auth {
        if inbound.socks5_user.is_empty() {
            return Err(anyhow!(
                "MasterDnsVPN socks5_auth=true requires a non-empty socks5_user"
            ));
        }
        if inbound.socks5_pass.is_empty() {
            return Err(anyhow!(
                "MasterDnsVPN socks5_auth=true requires a non-empty socks5_pass"
            ));
        }
    }
    Ok(())
}

/// Parse a JSON array of strings. Tolerates an empty string (treated as
/// `[]`) so an empty DB column doesn't make `validate()` panic on
/// invalid JSON.
fn parse_json_string_array(s: &str) -> std::result::Result<Vec<String>, String> {
    let trimmed = s.trim();
    if trimmed.is_empty() {
        return Ok(Vec::new());
    }
    let v: serde_json::Value = serde_json::from_str(trimmed)
        .map_err(|e| format!("not valid JSON: {e}"))?;
    let arr = v
        .as_array()
        .ok_or_else(|| "JSON value is not an array".to_string())?;
    let mut out = Vec::with_capacity(arr.len());
    for entry in arr {
        let s = entry
            .as_str()
            .ok_or_else(|| "array entry is not a string".to_string())?;
        out.push(s.to_string());
    }
    Ok(out)
}

fn bool_lit(b: bool) -> &'static str {
    if b {
        "true"
    } else {
        "false"
    }
}

/// Render a Rust string as a TOML basic string literal.
fn toml_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = std::fmt::Write::write_fmt(
                    &mut out,
                    format_args!("\\u{:04X}", c as u32),
                );
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn toml_string_array(items: &[String]) -> String {
    let mut out = String::from("[");
    for (i, s) in items.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&toml_string(s));
    }
    out.push(']');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn fixture() -> MdnsvpnInbound {
        MdnsvpnInbound {
            id: "mdnsvpn0".into(),
            domains: r#"["v.example.com"]"#.into(),
            port: 53,
            bind: "0.0.0.0".into(),
            encryption_method: 1,
            encryption_key: "0123456789abcdef0123456789abcdef".into(),
            protocol_type: "SOCKS5".into(),
            dns_upstream_servers: r#"["1.1.1.1:53","1.0.0.1:53"]"#.into(),
            forward_ip: String::new(),
            forward_port: 0,
            use_external_socks5: false,
            socks5_auth: false,
            socks5_user: String::new(),
            socks5_pass: String::new(),
            additional_config: String::new(),
            enabled: true,
            created_at: "now".into(),
            updated_at: "now".into(),
        }
    }

    #[test]
    fn happy_path_renders_required_sections() {
        let toml = generate(&fixture(), &PathBuf::from("/etc/awg/mdnsvpn"))
            .expect("generate succeeds");
        assert!(toml.contains(r#"DOMAIN = ["v.example.com"]"#));
        assert!(toml.contains("PROTOCOL_TYPE = \"SOCKS5\""));
        assert!(toml.contains("UDP_HOST = \"0.0.0.0\""));
        assert!(toml.contains("UDP_PORT = 53"));
        assert!(toml.contains("DATA_ENCRYPTION_METHOD = 1"));
        assert!(toml.contains("ENCRYPTION_KEY_FILE = \"/etc/awg/mdnsvpn/encrypt_key.txt\""));
        assert!(toml.contains("DNS_UPSTREAM_SERVERS = [\"1.1.1.1:53\", \"1.0.0.1:53\"]"));
        assert!(toml.contains("USE_EXTERNAL_SOCKS5 = false"));
        assert!(toml.contains("SOCKS5_AUTH = false"));
    }

    #[test]
    fn multi_domain_render() {
        let mut inbound = fixture();
        inbound.domains = r#"["a.example.com","b.example.com"]"#.into();
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains(r#"DOMAIN = ["a.example.com", "b.example.com"]"#));
    }

    #[test]
    fn additional_config_appended_verbatim() {
        let mut inbound = fixture();
        inbound.additional_config = "MAX_PACKET_SIZE = 65500\nUDP_READERS = 8\n".into();
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("# --- operator additional_config (verbatim) ---"));
        assert!(toml.ends_with("UDP_READERS = 8\n"));
    }

    #[test]
    fn tcp_mode_requires_forward_target() {
        let mut inbound = fixture();
        inbound.protocol_type = "TCP".into();
        // Missing forward_ip — should fail
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
        inbound.forward_ip = "10.0.0.5".into();
        inbound.forward_port = 1080;
        // Now succeeds
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("PROTOCOL_TYPE = \"TCP\""));
        assert!(toml.contains("FORWARD_IP = \"10.0.0.5\""));
        assert!(toml.contains("FORWARD_PORT = 1080"));
    }

    #[test]
    fn socks5_with_external_requires_forward_target() {
        let mut inbound = fixture();
        inbound.use_external_socks5 = true;
        // No forward target — should fail
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
        inbound.forward_ip = "192.168.1.100".into();
        inbound.forward_port = 1080;
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("USE_EXTERNAL_SOCKS5 = true"));
        assert!(toml.contains("FORWARD_IP = \"192.168.1.100\""));
    }

    #[test]
    fn socks5_auth_renders_credentials() {
        let mut inbound = fixture();
        inbound.use_external_socks5 = true;
        inbound.forward_ip = "10.0.0.5".into();
        inbound.forward_port = 1080;
        inbound.socks5_auth = true;
        inbound.socks5_user = "admin".into();
        inbound.socks5_pass = "secret".into();
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains("SOCKS5_AUTH = true"));
        assert!(toml.contains("SOCKS5_USER = \"admin\""));
        assert!(toml.contains("SOCKS5_PASS = \"secret\""));
    }

    #[test]
    fn rejects_invalid_port() {
        let mut inbound = fixture();
        inbound.port = 0;
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
        inbound.port = 70000;
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn rejects_empty_domains() {
        let mut inbound = fixture();
        inbound.domains = "[]".into();
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
        inbound.domains = "".into();
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn rejects_invalid_encryption_method() {
        let mut inbound = fixture();
        inbound.encryption_method = 7;
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn rejects_invalid_protocol_type() {
        let mut inbound = fixture();
        inbound.protocol_type = "HTTP".into();
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn rejects_missing_encryption_key() {
        let mut inbound = fixture();
        inbound.encryption_key = String::new();
        assert!(generate(&inbound, &PathBuf::from("/srv")).is_err());
    }

    #[test]
    fn toml_escapes_quotes_in_strings() {
        let mut inbound = fixture();
        inbound.forward_ip = r#"ev"il\path"#.into();
        inbound.protocol_type = "TCP".into();
        inbound.forward_port = 1080;
        let toml = generate(&inbound, &PathBuf::from("/srv")).unwrap();
        assert!(toml.contains(r#"FORWARD_IP = "ev\"il\\path""#));
    }
}
