//! Encryption-key generator + validator for MasterDnsVPN.
//!
//! The upstream `-genkey` flag produces a 16-byte random key encoded as
//! 32 lowercase-hex characters. We match that format exactly so a key
//! generated by awg-easy-rs is drop-in compatible with operators who
//! mix-and-match against vanilla MasterDnsVPN setups (e.g. for testing).
//!
//! The key is a single shared secret: every client uses the same value.
//! That's a property of MasterDnsVPN itself — its protocol has no
//! per-user secret slot. Per-user records in `mdnsvpn_clients_table`
//! are just bookkeeping for the share-link UX.

use anyhow::{anyhow, Result};
use rand::RngCore;

/// Length (in hex characters) of a freshly-generated key. 32 chars = 16
/// raw bytes — what upstream `mdnsvpn -genkey` produces. The encryption
/// engine is tolerant of longer keys (it KDFs internally for AES-256),
/// but matching upstream's default keeps share-formats interoperable.
pub const DEFAULT_KEY_HEX_LEN: usize = 32;

/// Minimum length operators are allowed to set. Below 16 hex chars
/// (8 bytes) every encryption method is meaningfully weakened — the
/// upstream README explicitly warns against short keys.
pub const MIN_KEY_HEX_LEN: usize = 16;

/// Generate a fresh random 16-byte key, hex-encoded. Uses `OsRng`, the
/// OS CSPRNG (same source the rest of awg-easy-rs uses for session
/// passwords + AmneziaWG private keys).
pub fn generate_key() -> String {
    let mut bytes = [0u8; DEFAULT_KEY_HEX_LEN / 2];
    rand::rngs::OsRng.fill_bytes(&mut bytes);
    hex::encode(bytes)
}

/// Validate a key-as-stored: must be lowercase or uppercase hex, even
/// length, and at least `MIN_KEY_HEX_LEN` characters. The mdnsvpn
/// binary itself accepts arbitrary ASCII for `ENCRYPTION_KEY`, but
/// constraining to hex keeps the share-format unambiguous (no
/// escaping issues in TOML / URLs / QR codes).
pub fn validate_key(key: &str) -> Result<()> {
    let k = key.trim();
    if k.is_empty() {
        return Err(anyhow!("encryption key must not be empty"));
    }
    if k.len() < MIN_KEY_HEX_LEN {
        return Err(anyhow!(
            "encryption key must be at least {MIN_KEY_HEX_LEN} hex chars (got {} chars)",
            k.len()
        ));
    }
    if k.len() % 2 != 0 {
        return Err(anyhow!(
            "encryption key must have an even number of hex characters (got {})",
            k.len()
        ));
    }
    if !k.chars().all(|c| c.is_ascii_hexdigit()) {
        return Err(anyhow!(
            "encryption key contains non-hex characters — only [0-9a-fA-F] are allowed"
        ));
    }
    Ok(())
}

/// Validate the integer encryption-method selector against the
/// upstream-defined set (0..=5). See `DATA_ENCRYPTION_METHOD` in the
/// upstream README for the meaning of each value.
pub fn validate_encryption_method(method: i64) -> Result<()> {
    match method {
        0..=5 => Ok(()),
        _ => Err(anyhow!(
            "DATA_ENCRYPTION_METHOD must be 0..=5 (got {method}). \
             0=None 1=XOR 2=ChaCha20 3=AES-128-GCM 4=AES-192-GCM 5=AES-256-GCM"
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_key_is_lowercase_hex_of_default_length() {
        for _ in 0..16 {
            let k = generate_key();
            assert_eq!(k.len(), DEFAULT_KEY_HEX_LEN);
            assert!(k.chars().all(|c| c.is_ascii_hexdigit()));
            assert!(k.chars().all(|c| !c.is_ascii_uppercase()));
        }
    }

    #[test]
    fn generated_keys_are_unique() {
        // Trivially-flakey collision check — but 16 bytes from OsRng has
        // a 2^-128 collision probability so this never spuriously fails.
        let a = generate_key();
        let b = generate_key();
        assert_ne!(a, b);
    }

    #[test]
    fn validate_accepts_hex_at_min_length() {
        validate_key("0123456789abcdef").unwrap();
    }

    #[test]
    fn validate_rejects_empty() {
        assert!(validate_key("").is_err());
        assert!(validate_key("   ").is_err());
    }

    #[test]
    fn validate_rejects_too_short() {
        assert!(validate_key("abcdef").is_err());
    }

    #[test]
    fn validate_rejects_odd_length() {
        assert!(validate_key("0123456789abcde").is_err());
    }

    #[test]
    fn validate_rejects_non_hex() {
        assert!(validate_key("zzzz5678zzzz5678").is_err());
    }

    #[test]
    fn validate_accepts_uppercase_hex() {
        // Hex itself is case-tolerant; we accept what the user types.
        validate_key("0123456789ABCDEF").unwrap();
    }

    #[test]
    fn validate_encryption_method_range() {
        for m in 0..=5 {
            validate_encryption_method(m).unwrap();
        }
        assert!(validate_encryption_method(-1).is_err());
        assert!(validate_encryption_method(6).is_err());
        assert!(validate_encryption_method(99).is_err());
    }
}
